{
 "title": "Performance",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (exported_endpoint) (rate(app_request_count_total{}[2m]))",
     "legendFormat": "{{exported_endpoint}}"
    }
   ]
  },
  {
   "title": "Error Rate (average per minute)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (exported_endpoint) (increase(app_request_count_total{http_status=~\"5.+\"}[1m]))",
     "legendFormat": "{{exported_endpoint}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "0.5 Quantile ",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, \n      sum by (le, exported_endpoint) \n         (rate(app_request_latency_seconds_bucket[5m]))\n) * 1000",
       "legendFormat": "{{exported_endpoint}}"
      }
     ]
    },
    {
     "title": "0.95 Quantile",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, \n      sum by (le, exported_endpoint) \n         (rate(app_request_latency_seconds_bucket[5m]))\n) * 1000",
       "legendFormat": "{{exported_endpoint}}"
      }
     ]
    },
    {
     "title": "0.99 Quantile ",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, \n      sum by (le, exported_endpoint) \n         (rate(app_request_latency_seconds_bucket[5m]))\n) * 1000",
       "legendFormat": "{{exported_endpoint}}"
      }
     ]
    },
    {
     "title": "1 Quantile",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(1, \n      sum by (le, exported_endpoint) \n         (rate(app_request_latency_seconds_bucket[5m]))\n) * 1000",
       "legendFormat": "{{exported_endpoint}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Nginx",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_count[2m]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Error Rate (average per minute)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (status) (increase(nginx_ingress_controller_request_duration_seconds_count{status=~\"5.+\"}[1m]))",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Latency 0.5 Quantile ",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5,\n\tsum by (le) \n\t(rate(nginx_ingress_controller_request_duration_seconds_bucket[5m]))\n) * 1000",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Latency 0.95 Quantile ",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95,\n\tsum by (le) \n\t(rate(nginx_ingress_controller_request_duration_seconds_bucket[5m]))\n) * 1000",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Latency 0.99 Quantile ",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99,\n\tsum by (le) \n\t(rate(nginx_ingress_controller_request_duration_seconds_bucket[5m]))\n) * 1000",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Latency 1 Quantile ",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(1,\n\tsum by (le) \n\t(rate(nginx_ingress_controller_request_duration_seconds_bucket[5m]))\n) * 1000",
       "legendFormat": "Total"
      }
     ]
    }
   ]
  },
  { "title": "Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{pod=~\"crud-service-.*\", image!=\"\", container_name!=\"POD\"}",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests_memory_bytes{pod=~\"crud-service-.*\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits_memory_bytes{pod=~\"crud-service-.*\"})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{pod=~\"crud-service-.*\", image!=\"\", container_name!=\"POD\"}[5m])",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests_cpu_cores{pod=~\"crud-service-.*\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits_cpu_cores{pod=~\"crud-service-.*\"})",
     "legendFormat": "Limits"
    },
    {
     "expr": "rate(container_cpu_cfs_throttled_seconds_total{pod=~\"crud-service-.*\", container_name!=\"POD\", image!=\"\"}[5m])",
     "legendFormat": "Throttling"
    }
   ]
  }
 ]
}