apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "crud-service-chart.fullname" . }}
spec:
  rules:
    - host: "{{ .Values.ingress.host }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "crud-service-chart.fullname" . }}
                port:
                  number: 8000
