apiVersion: v2
name: crud-service
description: A Helm chart for Kubernetes

type: application

version: 0.1.0
appVersion: "0.1.0"

dependencies:
  - name: postgresql
    version: 10.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    tags:
      - crud-service-database
